
name: product-catalog-dev-ci

permissions:
  id-token: write #Without it GitHub cannot generate the OIDC token.
  contents: write

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  APP_NAME: productcatalogservice
  APP_PATH: src/product-catalog
  DOCKER_FILE: src/product-catalog/Dockerfile
  HELM_VALUES_FILE: helm/productcatalog/values-dev.yaml
  TARGET_BRANCH: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: |
          cd ${{ env.APP_PATH }}
          go mod download
          go build -o product-catalog-service main.go

      - name: Unit Tests
        run: |
          cd ${{ env.APP_PATH }}
          go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          working-directory: ${{ env.APP_PATH }}

  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    needs:
      - build
  #    - code-quality

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   #arn:aws:iam::123456789012:role/github-actions-ecr-role        
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_PATH }}
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.APP_NAME }}:${{ github.run_id }}

  updatehelm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update Helm Values
        run: |
          sed -i 's|tag: .*|tag: "${{ github.run_id }}"|' "${{ env.HELM_VALUES_FILE }}"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "nagalakshmi896@gmail.com"
          git config --global user.name "nagalakshmi"

          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

          git add "${{ env.HELM_VALUES_FILE }}"

          git commit -m "CI: Update Product Catalog image tag" || true

          git push origin HEAD:${{ env.TARGET_BRANCH }}
